Mobil branch: In this pull request i finished the following activities:
Blessing600/Portfolio-setup-and-mobile-first pull request #1
Opened 2022-12-02 13:53 UTC by Blessing600

1. Add new gitignore rules
2. Add Work section in html & create css rules for classes.
3. Fix Linters errors in styles.css
4. Updated my Style.CSS file (Styl)
5. Updated my Img folder

2022-12-02 14:09 UTC, emmiiorji requested changes
Hi @Blessing600, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Ouch-gifs-38715704-365-199](https://user-images.githubusercontent.com/20554583/203522872-2c5eafd3-e90b-4c90-859a-320f26e8a84d.gif)

You have submitted a project that's not using the [updated readme template](https://github.com/microverseinc/readme-template). Kindly modify your readme file using the newly recommended template as this is required to receive a review henceforth. Check the announcement channel on slack for more information about the new template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-03 10:52 UTC, DuaneDave requested changes
Hi @Blessing600 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Beautiful design 💯 
✅ Nice code structure 💯 
✅ Awesome PR summary 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 10:52 UTC, DuaneDave commented on index.html
> +            <a class="logo-title" href="index.html">Ogbodo~Juliet</a>
I suggest using the correct font family for the logo as specified in the Figma template.

On Figma it is Poppins but you are currently using georgia

2022-12-03 10:52 UTC, DuaneDave commented on index.html
> +            </div>
Please make this image a background image instead of using an image tag to avoid screen readers from reading this as part of a page content which can sometimes be a bad user experience as it has no meaning to the page (its just for decoration)

2022-12-03 10:52 UTC, DuaneDave commented on index.html
> +            </ul>
[OPTIONAL]  I suggest trying to link these social links with your social media handles to make contacting you much easier.

2022-12-03 10:52 UTC, DuaneDave commented on index.html
> +            </div>
please the correct font family for your topographies as specified in the Figma design to make your website match the Figma design

2022-12-03 10:52 UTC, DuaneDave commented on index.html
> +    <section class="section1">
currently, the background color is black which is different from the Figma design. Kindly use the correct background colour specified in the Figma template `#1C1A19` to make the page more visually appealing.

2022-12-03 10:52 UTC, DuaneDave commented on styles.css
> +@media screen and (max-width: 375px) {
please do not use media queries since it is a mobile-first approach, kindly move all the codes inside this media query outside as this will be following the current milestone's work and it will reduce the amount of code needed for your next milestone.

2022-12-03 10:52 UTC, DuaneDave commented on styles.css
> +    display: flex;
Please create a class responsible for adding `display: flex;` to avoid repeating yourself.

Like this...


```
.flex {
  display: flex;
}
```

You can then add this to your HTML tags as you would a normal class.

2022-12-03 13:02 UTC, algerina requested changes
Hi @Blessing600 , 

You've done an amazing job fir 👏 💯 👍
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Highlights
  -  Linters are passing! 
  - Your project looks awesome!

<img src="https://media1.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>

## Required Changes ♻️

- [ ] Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2022-12-03 13:02 UTC, algerina commented on styles.css
> +
- [ ] Kindly replace the background color from Black to `#1C1A19` as requested by the previous reviewer.

2022-12-03 13:02 UTC, algerina commented on index.html
> +                <li><a href="https://twitter.com/Juliet1Ogbodo"><i class="fa-brands fa-twitter fas"></i></a></li>
- [ Optional] You have a duplicated Twitter icon, kindly delete it.

2022-12-03 13:32 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Blessing600 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* Github flow is used correctly ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_

## Optional:
- [ ] Please consider following the best practices when writing commit messages. They should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" 💯 

_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 13:32 UTC, ha-manel commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
[Optional]

- [ ] This is a core requirement but I'm marking it as optional since the previous reviewers didn't mention it. Please consider using the new README [template](https://github.com/microverseinc/readme-template) for this project and all future Microverse projects 👍

2022-12-03 13:32 UTC, ha-manel commented on index.html
> +            </div>
- [ ] As mentioned by the previous reviewers, kindly update the `background-color` of the headline section to `#1C1A19` to match the design in Figma.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/205443069-1d08c709-2dd4-4c3a-9fb2-df527c303f7b.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/205443080-3497fb81-d532-48c2-8c25-4f904846f9d8.png)

[Optional]

- [ ] Please consider adding the `background-image` to this section to match the design in Figma 👍

2022-12-03 13:32 UTC, ha-manel commented on styles.css
> +/* stylelint-disable no-descending-specificity */
[Optional]

- [ ] Kindly avoid disabling linters, instead, I recommend you try to work around them because they force us to use best practices. This is marked as optional since it wasn't noticed by the previous reviewers but it's a requirement in every Microverse project.

2022-12-03 14:13 UTC, amejid approved these changes
Hi @Blessing600, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Correct use of Github flow :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 14:14 UTC, merged

2022-12-08 07:12 UTC, Blessing600 commented
I have Merged It , it still not showing completed on my dashboard 
![image](https://user-images.githubusercontent.com/69908280/206381855-264c246f-7a13-4878-92dc-5cc757e30653.png)

2022-12-08 07:13 UTC, Blessing600 commented
What will I do to solve this issue? 
Thanks