Portfolio: finish mobile version
Blessing600/Portfolio-setup-and-mobile-first pull request #2
Opened 2022-12-03 15:30 UTC by Blessing600

1. Addition of the about section.
2.  Addition of the work section.
3. updates my Readme file
4. Fix linters errors in styles.css

2022-12-03 15:42 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi @Blessing600 
I'm sure you put a lot of effort into this project but this PR is invalid because your README file doesn't follow the new template😓Kindly refer to this [README](https://github.com/microverseinc/readme-template) file and use it for all the projects 👍  

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 20:27 UTC, levy002 requested changes
## Hello @Blessing600   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to wrap your stack list in the `ul` tag and each one is wrapped in `li` tag for semantic reasons. :wink:  Please make sure to change that for every project.
    
    ![image](https://user-images.githubusercontent.com/87197412/205459034-ce0e4888-1c35-44e1-afe2-d9a8d4214761.png)

- [ ] Kindly make sure to use CSS background properties to insert the background image in the  `About me` section. It is not a best practice to add your background image in an HTML file. I highly recommend you to change that in order to meet the project requirement. :wink: 

     ![image](https://user-images.githubusercontent.com/87197412/205459258-943eb487-4e9b-42eb-9974-917fc5bb41c5.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to align the contents for the `works` by using `GRID` as requested in the project requirements. :wink:

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to style the button correctly in order to look like the provided ones on the Figma design. :wink:  
   - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/205459599-be461a36-c4a5-4fb5-8dd2-6c33f48771de.png)

   - ### Figma design
   
    ![image](https://user-images.githubusercontent.com/87197412/205459579-dafcf2a8-a15a-499d-9b84-c7ffb21ad54f.png)

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +  margin-top: 1rem;
- [ ] Kind make sure to follow the best practices by following the DRY practice which stands for Don't Repeat Yourself. I highly recommend to not repeating yourself in your CSS file.

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to change your background colour on your stack list in order to meet the provided Figma design. :wink: 

 - ### YOUR DESIGN
     ![image](https://user-images.githubusercontent.com/87197412/205459807-3287d709-f8c7-465a-ab56-7cb5e1bfbb14.png)

 - ### Figma design
    ![image](https://user-images.githubusercontent.com/87197412/205459826-18c2a082-dc2e-40d4-a368-1993075cc1b3.png)

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +
- [ ] Kindly make sure to align your project card contents using `flexbox` in order to meet the project requirement. :wink:

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +
- [ ] Kindly make sure to use the same typography styles on the `see project` button as the one on the provided Figma design. :wink: 

   - ### Your design
    ![image](https://user-images.githubusercontent.com/87197412/205460112-5338c373-2cd7-46e9-9a7c-52c565cec56f.png)

  - ### Figma design
     ![image](https://user-images.githubusercontent.com/87197412/205460130-8de67ddb-fbc6-4e22-8a13-95b2ff1b54ab.png)

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to use the same typography styles on the `About me` title in order to meet the provided Figma design. :wink: 

   - ### Your design
      ![image](https://user-images.githubusercontent.com/87197412/205460314-f2f93669-e92a-433c-b07d-636211efffc9.png)

   - ### Figma design
     ![image](https://user-images.githubusercontent.com/87197412/205460344-8721f623-6a80-46a6-a2d6-8c4200fefe11.png)

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +
-[ ] Kindly make sure to use the same typography in `Get my resume` in order to meet the project requirement.

   - ### Your design
      ![image](https://user-images.githubusercontent.com/87197412/205460487-653126e0-9344-492a-8b37-49baf7029c02.png)

   - ### Figma design
   ![image](https://user-images.githubusercontent.com/87197412/205460508-21ba206e-2294-4e13-b921-4f471463140d.png)

2022-12-03 20:27 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to align the contents of this `About me` section using `flexbox` in order to meet the project requirement. :wink:

2022-12-07 15:43 UTC, BregornOriginal requested changes
## Hi @Blessing600  

## Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![cat-driving-serious](https://user-images.githubusercontent.com/93630700/206224188-7fcd282d-e078-42b2-b21a-f844c4a52247.gif)

 ## Highlights

✅ Linters are passing
✅ Correct use of GitHub Flow
✅ Good commit history
✅ Good job making some of the changes requested by the previous reviewer 🥇 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 15:43 UTC, BregornOriginal commented on styles.css
> +  text-align: center;
- [ ] Kindly as the previous reviewer suggested. Make your SEE PROJECT button looks similar to the one on FIGMA design, it's bigger than yours

![image](https://user-images.githubusercontent.com/93630700/206222311-c9c421a8-2b91-46ac-9517-2947b2337c41.png)

2022-12-07 15:43 UTC, BregornOriginal commented on index.html
> +                        <li>bookstrap</li>
- [OPTIONAL] Kindly correct the name of this technology. It's Bootstrap 💯

2022-12-07 15:43 UTC, BregornOriginal commented on styles.css
> +.about-section-mainbutton .tag-2 {
- [ ] On the about section is missing the image on the background. 

![image](https://user-images.githubusercontent.com/93630700/206222862-ee519ace-cca3-4b22-b364-ffe1c3226063.png)

2022-12-07 15:43 UTC, BregornOriginal commented on styles.css
> +}
- [ ] Kindly as the previous reviewer mentioned. Correct the padding and size of this button to be similar to the FIGMA design

![image](https://user-images.githubusercontent.com/93630700/206223666-ce58a32f-1d32-4eea-8d38-32707a1eee78.png)

2022-12-08 04:43 UTC, Blessing600 commented on styles.css
> +.about-section-mainbutton .tag-2 {
Sorry is Optional (decoration )

2022-12-08 05:54 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Blessing600 👋, 

Good job implementing the changes request by the previous reviewers :clap: 
There are some issues that you still need to work on to go to the next project, but you are almost there! :cry: 

## To Highlight 🎉

- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. :heavy_check_mark: 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 05:54 UTC, iambenkis commented on index.html
> +                    </ul>
- [ ][**OPTIONAL**] You used a good naming on other technology :weary: , but you use ```Bookstrap```. Kindly change that to ```Bootstrap```.

2022-12-08 05:54 UTC, iambenkis commented on index.html
> +              </div>
- [ ] You performed :+1:  in this project correcting the changes gave by previous reviewers. However, you did not correct this part ```Get My Resume```. According to the Figma design. Kindly change that accordingly.  Remember , to stick to a design means make sure the font, colours, images, text, margins look the same as  in the template design :100: 

### Your design

![Screenshot from 2022-12-08 07-29-39](https://user-images.githubusercontent.com/80458199/206365167-8f2753ef-9706-48c1-bfc1-68fc6d5693ee.png)

### Figma design

![Screenshot from 2022-12-08 07-29-59](https://user-images.githubusercontent.com/80458199/206365262-446d10dc-b8f5-47d0-8826-9e8fcdad285a.png)

- [ ] **In order to get your project approved you should correct all the changes suggested by previous reviewers.**

2022-12-08 05:54 UTC, iambenkis commented on index.html
> +                </div>
- [ ] [**OPTIONAL**] Kindly make sure this section is well centred according to the Figma design :100: **Remember , to stick to a design means make sure the font, colours, images, text, margins look the same as in the template design :100:**

### Your design

![Screenshot from 2022-12-08 07-39-56](https://user-images.githubusercontent.com/80458199/206367259-2b423eae-e788-490a-9bb4-ede76ed5dafa.png)

### Figma Design

![Screenshot from 2022-12-08 07-44-49](https://user-images.githubusercontent.com/80458199/206367347-7e9af7cf-c8e3-4f91-8a93-24b57fb2f64e.png)

**This is a crucial part of the requirements, there are optionals just because the previous reviewers did not see them. It says that human has limits but trust you enough to limit your performance to the limits of human :smile_cat: , so make sure you correct also the _OPTIONAL_ comments**

2022-12-08 07:09 UTC, roshan-bajgain approved these changes
Hi @Blessing600, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 07:16 UTC, merged